//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZCGZM_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbCategory
    {
        public int categoryId { get; set; }
        public string categoryName { get; set; }
        public int parentId { get; set; }
        public int categoryState { get; set; }
        public int categoryType { get; set; }
        public int sortNumber { get; set; }
        public string categoryInfo { get; set; }
        public string categoryNameEN { get; set; }
        public string categoryInfoEN { get; set; }
    }
}
