//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZCGZM_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbImage
    {
        public int imageId { get; set; }
        public string imageURL { get; set; }
        public int imageType { get; set; }
        public int imageState { get; set; }
        public int bindId { get; set; }
    }
}
