//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZCGZM_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbNews
    {
        public int newsId { get; set; }
        public string newsTitle { get; set; }
        public System.DateTime newsPublishTime { get; set; }
        public string newsContentHtmlString { get; set; }
        public int newsState { get; set; }
        public Nullable<int> newsType { get; set; }
        public string newsTitleEN { get; set; }
        public string newsContentHtmlStringEN { get; set; }
    }
}
