//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HZCGZM_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProduct
    {
        public int productId { get; set; }
        public string productName { get; set; }
        public string productNumber { get; set; }
        public int productCategoryId { get; set; }
        public int productSubcategoryId { get; set; }
        public string productDetailHtmlString { get; set; }
        public int productState { get; set; }
        public string productNameEN { get; set; }
        public string productDetailHtmlStringEN { get; set; }
    }
}
