//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.lang", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于我们 的本地化字符串。
        /// </summary>
        internal static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 地址 的本地化字符串。
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 浙江省杭州市临安花桥路68号 的本地化字符串。
        /// </summary>
        internal static string address_info {
            get {
                return ResourceManager.GetString("address_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品册 的本地化字符串。
        /// </summary>
        internal static string catalog {
            get {
                return ResourceManager.GetString("catalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 公司简介 的本地化字符串。
        /// </summary>
        internal static string company_profile {
            get {
                return ResourceManager.GetString("company_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系我们 的本地化字符串。
        /// </summary>
        internal static string contact_us {
            get {
                return ResourceManager.GetString("contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 点击下载 的本地化字符串。
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮箱 的本地化字符串。
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 传真 的本地化字符串。
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所在位置 的本地化字符串。
        /// </summary>
        internal static string location {
            get {
                return ResourceManager.GetString("location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更多 的本地化字符串。
        /// </summary>
        internal static string more {
            get {
                return ResourceManager.GetString("more", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关于我们 的本地化字符串。
        /// </summary>
        internal static string nav_about_us {
            get {
                return ResourceManager.GetString("nav_about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用领域 的本地化字符串。
        /// </summary>
        internal static string nav_application {
            get {
                return ResourceManager.GetString("nav_application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 联系我们 的本地化字符串。
        /// </summary>
        internal static string nav_contact_us {
            get {
                return ResourceManager.GetString("nav_contact_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下载专区 的本地化字符串。
        /// </summary>
        internal static string nav_download {
            get {
                return ResourceManager.GetString("nav_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        internal static string nav_home {
            get {
                return ResourceManager.GetString("nav_home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻资讯 的本地化字符串。
        /// </summary>
        internal static string nav_news_center {
            get {
                return ResourceManager.GetString("nav_news_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用支持 的本地化字符串。
        /// </summary>
        internal static string nav_oem_support {
            get {
                return ResourceManager.GetString("nav_oem_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品中心 的本地化字符串。
        /// </summary>
        internal static string nav_products {
            get {
                return ResourceManager.GetString("nav_products", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新闻资讯 的本地化字符串。
        /// </summary>
        internal static string news_center {
            get {
                return ResourceManager.GetString("news_center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用支持 的本地化字符串。
        /// </summary>
        internal static string oem_support {
            get {
                return ResourceManager.GetString("oem_support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包装设计 的本地化字符串。
        /// </summary>
        internal static string package_design {
            get {
                return ResourceManager.GetString("package_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电话 的本地化字符串。
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮编 的本地化字符串。
        /// </summary>
        internal static string post {
            get {
                return ResourceManager.GetString("post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产流程 的本地化字符串。
        /// </summary>
        internal static string producing_process {
            get {
                return ResourceManager.GetString("producing_process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品详情 的本地化字符串。
        /// </summary>
        internal static string product_detail {
            get {
                return ResourceManager.GetString("product_detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品名称 的本地化字符串。
        /// </summary>
        internal static string product_name {
            get {
                return ResourceManager.GetString("product_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产品编号 的本地化字符串。
        /// </summary>
        internal static string product_number {
            get {
                return ResourceManager.GetString("product_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 样品设计 的本地化字符串。
        /// </summary>
        internal static string promotion_material_design {
            get {
                return ResourceManager.GetString("promotion_material_design", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 的本地化字符串。
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
    }
}
